#import "ABMCShortcutPanelController.h"
#import <objc/message.h>
#import <dlfcn.h>

static NSCache *ABMCPanelIconCache(void) { static NSCache *cache; static dispatch_once_t once; dispatch_once(&once, ^{ cache=[NSCache new]; cache.countLimit=24; }); return cache; }
static UIImage *PanelIcon(NSDictionary *item, CGFloat side) {
    NSString *key=[NSString stringWithFormat:@"%@:%@:%.0f",item[@"glyph"]?:@0,item[@"color"]?:@0,side]; UIImage *cached=[ABMCPanelIconCache() objectForKey:key]; if(cached)return cached;
    UIImage *saved=[UIImage imageWithData:item[@"iconData"]]; if(saved){[ABMCPanelIconCache() setObject:saved forKey:key];return saved;}
    @try { dlopen("/System/Library/PrivateFrameworks/VoiceShortcutClient.framework/VoiceShortcutClient",RTLD_LAZY|RTLD_LOCAL);Class iconClass=NSClassFromString(@"WFWorkflowIcon"),drawer=NSClassFromString(@"WFWorkflowIconDrawer");SEL make=NSSelectorFromString(@"initWithBackgroundColorValue:glyphCharacter:customImageData:"),draw=NSSelectorFromString(@"imageWithIcon:size:background:"),ui=NSSelectorFromString(@"UIImage");if(![iconClass instancesRespondToSelector:make]||![drawer respondsToSelector:draw])return nil;id icon=((id(*)(id,SEL,long long,unsigned short,id))objc_msgSend)([iconClass alloc],make,[item[@"color"] longLongValue],(unsigned short)[item[@"glyph"] integerValue],nil);id rendered=icon?((id(*)(id,SEL,id,CGSize,BOOL))objc_msgSend)(drawer,draw,icon,CGSizeMake(side,side),YES):nil;UIImage *result=[rendered isKindOfClass:UIImage.class]?rendered:([rendered respondsToSelector:ui]?((id(*)(id,SEL))objc_msgSend)(rendered,ui):nil);if(result)[ABMCPanelIconCache() setObject:result forKey:key];return result;} @catch(NSException *e){return nil;}
}
static CGFloat ABMCPanelIconSide(void) { CFPropertyListRef v=CFPreferencesCopyAppValue(CFSTR("unifiedIconSize"),CFSTR("com.huynguyen.actionbuttonmulticlick"));CGFloat n=v&&CFGetTypeID(v)==CFNumberGetTypeID()?[(__bridge NSNumber*)v doubleValue]:30.0;if(v)CFRelease(v);return MIN(56.0,MAX(24.0,n)); }
static NSDictionary *PanelDisplayItem(NSDictionary *item) { CFPropertyListRef value=CFPreferencesCopyAppValue(CFSTR("presentationOverrides"),CFSTR("com.huynguyen.actionbuttonmulticlick"));NSDictionary *all=value&&CFGetTypeID(value)==CFDictionaryGetTypeID()?(__bridge NSDictionary*)value:nil;NSDictionary *override=[all[[@"shortcut." stringByAppendingString:item[@"identifier"]?:@""]] copy];if(value)CFRelease(value);if(![override isKindOfClass:NSDictionary.class])return item;NSMutableDictionary *shown=[item mutableCopy];if([override[@"title"] isKindOfClass:NSString.class]&&[override[@"title"] length])shown[@"name"]=override[@"title"];if([override[@"icon"] isKindOfClass:NSString.class]&&[override[@"icon"] length])shown[@"displayIcon"]=override[@"icon"];return shown; }

@implementation ABMCShortcutPanelController { NSArray *_items; void (^_selection)(NSDictionary *); UIView *_card; }
- (void)viewDidLayoutSubviews {[super viewDidLayoutSubviews];if(_card){CGRect f=_card.frame;f.origin.x=8;f.size.width=self.view.bounds.size.width-16;f.origin.y=MAX(16.0,self.view.safeAreaInsets.top+16.0);_card.frame=f;}}
- (instancetype)initWithItems:(NSArray *)items selection:(void (^)(NSDictionary *))selection { if((self=[super init])){_items=[items copy];_selection=[selection copy];self.modalPresentationStyle=UIModalPresentationOverFullScreen;self.modalTransitionStyle=UIModalTransitionStyleCrossDissolve;}return self; }
- (void)viewDidLoad {
    [super viewDidLoad]; self.view.backgroundColor=UIColor.clearColor;
    UITapGestureRecognizer *tap=[[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(backgroundTap:)];tap.cancelsTouchesInView=NO;[self.view addGestureRecognizer:tap];
    NSUInteger count=MIN(_items.count,(NSUInteger)8),rows=(count+3)/4; CGFloat width=self.view.bounds.size.width-16.0,rowHeight=96.0,height=32.0+rows*rowHeight;
    // On Dynamic-Island devices safeAreaInsets.top is the island's bottom.
    CGFloat top=MAX(16.0,self.view.safeAreaInsets.top+16.0); _card=[[UIView alloc]initWithFrame:CGRectMake(8,top,width,height)];_card.autoresizingMask=UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleBottomMargin;_card.backgroundColor=UIColor.systemBackgroundColor;_card.layer.cornerRadius=34;_card.clipsToBounds=YES;_card.alpha=0;_card.transform=CGAffineTransformMakeScale(.94,.94);[self.view addSubview:_card];
    CGFloat column=width/4.0,side=ABMCPanelIconSide();
    for(NSUInteger i=0;i<count;i++) { NSDictionary *item=PanelDisplayItem(_items[i]);UIButton *button=[UIButton buttonWithType:UIButtonTypeCustom];button.frame=CGRectMake(i%4*column,16+i/4*rowHeight,column,rowHeight);button.tag=i;[button addTarget:self action:@selector(select:) forControlEvents:UIControlEventTouchUpInside];
        UIImage *image=PanelIcon(item,side);if([item[@"displayIcon"] length])image=[UIImage systemImageNamed:item[@"displayIcon"] withConfiguration:[UIImageSymbolConfiguration configurationWithPointSize:side weight:UIImageSymbolWeightMedium]] ?: image;UIImageView *icon=[[UIImageView alloc]initWithFrame:CGRectMake((column-side)/2,0,side,side)];icon.image=image?:[UIImage systemImageNamed:@"square.stack.3d.up.fill"];icon.contentMode=UIViewContentModeScaleAspectFit;icon.backgroundColor=image?UIColor.clearColor:UIColor.systemGray5Color;icon.layer.cornerRadius=side*.5;icon.clipsToBounds=YES;[button addSubview:icon];
        UILabel *label=[[UILabel alloc]initWithFrame:CGRectMake(3,side+7,column-6,22)];label.text=item[@"name"]?:@"快捷指令";label.textColor=UIColor.labelColor;label.font=[UIFont systemFontOfSize:12 weight:UIFontWeightRegular];label.textAlignment=NSTextAlignmentCenter;label.lineBreakMode=NSLineBreakByTruncatingTail;label.adjustsFontSizeToFitWidth=YES;label.minimumScaleFactor=.75;label.userInteractionEnabled=NO;[button addSubview:label];[_card addSubview:button];
    }
}
- (void)viewDidAppear:(BOOL)animated {[super viewDidAppear:animated];[UIView animateWithDuration:.22 delay:0 options:UIViewAnimationOptionCurveEaseOut animations:^{self.view.backgroundColor=[[UIColor blackColor]colorWithAlphaComponent:.18];self->_card.alpha=1;self->_card.transform=CGAffineTransformIdentity;} completion:nil];}
- (void)viewDidDisappear:(BOOL)animated {[super viewDidDisappear:animated];if(!self.presentedViewController){_selection=nil;_items=nil;}}
- (void)closeThen:(dispatch_block_t)completion {[UIView animateWithDuration:.18 delay:0 options:UIViewAnimationOptionCurveEaseIn animations:^{self.view.backgroundColor=UIColor.clearColor;self->_card.alpha=0;self->_card.transform=CGAffineTransformMakeScale(.94,.94);} completion:^(__unused BOOL done){self->_selection=nil;self->_items=nil;[ABMCPanelIconCache() removeAllObjects];[self dismissViewControllerAnimated:NO completion:completion];}];}
- (void)select:(UIButton *)sender { NSDictionary *item=_items[sender.tag];void(^block)(NSDictionary*)=[_selection copy];[self closeThen:^{if(block)block(item);}]; }
- (void)backgroundTap:(UITapGestureRecognizer *)tap { if(!CGRectContainsPoint(_card.frame,[tap locationInView:self.view]))[self closeThen:nil]; }
@end
