#import "ABMCShortcutPanelController.h"
#import <objc/message.h>
#import <dlfcn.h>

static UIImage *PanelIcon(NSDictionary *item) {
    UIImage *saved=[UIImage imageWithData:item[@"iconData"]]; if(saved)return saved;
    @try { dlopen("/System/Library/PrivateFrameworks/VoiceShortcutClient.framework/VoiceShortcutClient",RTLD_LAZY|RTLD_LOCAL);Class iconClass=NSClassFromString(@"WFWorkflowIcon"),drawer=NSClassFromString(@"WFWorkflowIconDrawer");SEL make=NSSelectorFromString(@"initWithBackgroundColorValue:glyphCharacter:customImageData:"),draw=NSSelectorFromString(@"imageWithIcon:size:background:"),ui=NSSelectorFromString(@"UIImage");if(![iconClass instancesRespondToSelector:make]||![drawer respondsToSelector:draw])return nil;id icon=((id(*)(id,SEL,long long,unsigned short,id))objc_msgSend)([iconClass alloc],make,[item[@"color"] longLongValue],(unsigned short)[item[@"glyph"] integerValue],nil);id rendered=icon?((id(*)(id,SEL,id,CGSize,BOOL))objc_msgSend)(drawer,draw,icon,CGSizeMake(72,72),YES):nil;return[rendered isKindOfClass:UIImage.class]?rendered:([rendered respondsToSelector:ui]?((id(*)(id,SEL))objc_msgSend)(rendered,ui):nil);} @catch(NSException *e){return nil;}
}

@implementation ABMCShortcutPanelController { NSArray *_items; void (^_selection)(NSDictionary *); UIView *_card; }
- (instancetype)initWithItems:(NSArray *)items selection:(void (^)(NSDictionary *))selection { if((self=[super init])){_items=[items copy];_selection=[selection copy];self.modalPresentationStyle=UIModalPresentationOverFullScreen;self.modalTransitionStyle=UIModalTransitionStyleCrossDissolve;}return self; }
- (void)viewDidLoad {[super viewDidLoad];self.view.backgroundColor=[[UIColor blackColor]colorWithAlphaComponent:.20];UITapGestureRecognizer*t=[[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(backgroundTap:)];t.cancelsTouchesInView=NO;[self.view addGestureRecognizer:t];NSUInteger count=MIN(_items.count,(NSUInteger)8),rows=(count+3)/4;CGFloat width=MIN(self.view.bounds.size.width-36,440),height=32+rows*142;_card=[[UIView alloc]initWithFrame:CGRectMake((self.view.bounds.size.width-width)/2,(self.view.bounds.size.height-height)/2,width,height)];_card.autoresizingMask=UIViewAutoresizingFlexibleTopMargin|UIViewAutoresizingFlexibleBottomMargin|UIViewAutoresizingFlexibleLeftMargin|UIViewAutoresizingFlexibleRightMargin;_card.backgroundColor=UIColor.systemBackgroundColor;_card.layer.cornerRadius=34;_card.clipsToBounds=YES;[self.view addSubview:_card];CGFloat step=width/4.0;for(NSUInteger i=0;i<count;i++){NSDictionary*item=_items[i];UIButton*b=[UIButton buttonWithType:UIButtonTypeCustom];b.frame=CGRectMake(i%4*step,16+i/4*142,step,126);b.tag=i;[b addTarget:self action:@selector(select:) forControlEvents:UIControlEventTouchUpInside];UIImage*image=PanelIcon(item);UIImageView*icon=[[UIImageView alloc]initWithFrame:CGRectMake((step-88)/2,0,88,88)];icon.image=image?:[UIImage systemImageNamed:@"square.stack.3d.up.fill"];icon.contentMode=UIViewContentModeScaleAspectFit;icon.backgroundColor=image?UIColor.clearColor:[UIColor.systemGray5Color colorWithAlphaComponent:.8];icon.layer.cornerRadius=44;icon.clipsToBounds=YES;[b addSubview:icon];UILabel*label=[[UILabel alloc]initWithFrame:CGRectMake(4,94,step-8,38)];label.text=item[@"name"]?:@"快捷指令";label.textColor=UIColor.labelColor;label.font=[UIFont systemFontOfSize:16 weight:UIFontWeightMedium];label.textAlignment=NSTextAlignmentCenter;label.numberOfLines=2;label.adjustsFontSizeToFitWidth=YES;label.userInteractionEnabled=NO;[b addSubview:label];[_card addSubview:b];}}
- (void)select:(UIButton *)sender { NSDictionary*item=_items[sender.tag];void(^block)(NSDictionary*)=_selection;[self dismissViewControllerAnimated:YES completion:^{if(block)block(item);}]; }
- (void)backgroundTap:(UITapGestureRecognizer *)tap { if(!CGRectContainsPoint(_card.frame,[tap locationInView:self.view]))[self dismissViewControllerAnimated:YES completion:nil]; }
@end
