#import "ABMCUIHelpers.h"
#import <objc/message.h>
#import <dlfcn.h>

static id ABMCValue(id object, NSString *name) { SEL s=NSSelectorFromString(name); return object&&[object respondsToSelector:s]?((id(*)(id,SEL))objc_msgSend)(object,s):nil; }
static id ABMCProxy(NSString *bundleID) { Class c=NSClassFromString(@"LSApplicationWorkspace");id w=ABMCValue(c,@"defaultWorkspace");SEL s=NSSelectorFromString(@"applicationProxyForBundleIdentifier:");return w&&[w respondsToSelector:s]?((id(*)(id,SEL,id))objc_msgSend)(w,s,bundleID):nil; }
static id ABMCAppList(void) { dlopen("/var/jb/usr/lib/libapplist.dylib",RTLD_LAZY|RTLD_LOCAL);dlopen("/usr/lib/libapplist.dylib",RTLD_LAZY|RTLD_LOCAL);Class c=NSClassFromString(@"ALApplicationList");SEL s=NSSelectorFromString(@"sharedApplicationList");return c&&[c respondsToSelector:s]?((id(*)(id,SEL))objc_msgSend)(c,s):nil; }
static UIImage *ABMCResizeIcon(UIImage *image) { if(!image)return nil;CGFloat side=30;UIGraphicsBeginImageContextWithOptions(CGSizeMake(side,side),NO,UIScreen.mainScreen.scale);[image drawInRect:CGRectMake(0,0,side,side)];UIImage*r=UIGraphicsGetImageFromCurrentImageContext();UIGraphicsEndImageContext();return r; }

UIImage *ABMCAppListIcon(NSString *bundleID, NSUInteger size) { id list=ABMCAppList();SEL s=NSSelectorFromString(@"iconOfSize:forDisplayIdentifier:");if(list&&bundleID.length&&[list respondsToSelector:s]){UIImage*i=((id(*)(id,SEL,NSUInteger,id))objc_msgSend)(list,s,size,bundleID);if([i isKindOfClass:[UIImage class]])return ABMCResizeIcon(i);}return nil; }
NSString *ABMCAppListDisplayName(NSString *bundleID) { id list=ABMCAppList();if(!list||!bundleID.length)return nil;for(NSString*k in @[@"displayName",@"name",@"localizedName"]){SEL s=NSSelectorFromString(@"valueForKey:forDisplayIdentifier:");if([list respondsToSelector:s]){id v=((id(*)(id,SEL,id,id))objc_msgSend)(list,s,k,bundleID);if([v isKindOfClass:[NSString class]]&&v.length)return v;}}return nil; }

static UIImage *ABMCImageFromBundle(NSURL *url) { if(!url)return nil;NSBundle*b=[NSBundle bundleWithURL:url];NSDictionary*info=b.infoDictionary;NSMutableOrderedSet*names=[NSMutableOrderedSet orderedSet];NSDictionary*icons=info[@"CFBundleIcons"]?:info[@"CFBundleIcons~ipad"];NSDictionary*primary=[icons isKindOfClass:[NSDictionary class]]?icons[@"CFBundlePrimaryIcon"]:nil;NSArray*files=[primary isKindOfClass:[NSDictionary class]]?primary[@"CFBundleIconFiles"]:nil;if([files isKindOfClass:[NSArray class]])[names addObjectsFromArray:files];NSString*legacy=info[@"CFBundleIconFile"];if(legacy.length)[names addObject:legacy];[names addObjectsFromArray:@[@"AppIcon",@"AppIcon60x60",@"Icon60",@"Icon"]];for(NSString*n in names){NSString*stem=[n stringByDeletingPathExtension];UIImage*i=[UIImage imageNamed:stem inBundle:b compatibleWithTraitCollection:nil];if(i)return i;for(NSString*c in @[[stem stringByAppendingString:@"@2x.png"],[stem stringByAppendingString:@"@3x.png"],[stem stringByAppendingPathExtension:@"png"]]){i=[UIImage imageWithContentsOfFile:[url.path stringByAppendingPathComponent:c]];if(i)return i;}}return nil; }
UIImage *ABMCIconImageForProxy(id proxy) { if(!proxy)return nil;NSString*bid=ABMCValue(proxy,@"bundleIdentifier");UIImage*i=ABMCAppListIcon(bid,59);if(i)return i;@try{for(NSString*n in @[@"icon",@"applicationIcon",@"primaryIcon"]){id v=ABMCValue(proxy,n);if([v isKindOfClass:[UIImage class]])return ABMCResizeIcon(v);}for(NSString*n in @[@"primaryIconDataForVariant:",@"iconDataForVariant:"]){SEL s=NSSelectorFromString(n);for(NSInteger v=0;v<32&&[proxy respondsToSelector:s];v++){NSData*d=((id(*)(id,SEL,NSInteger))objc_msgSend)(proxy,s,v);i=[d isKindOfClass:[NSData class]]?[UIImage imageWithData:d]:nil;if(i)return ABMCResizeIcon(i);}}i=ABMCImageFromBundle(ABMCValue(proxy,@"bundleURL"));if(i)return ABMCResizeIcon(i);}@catch(NSException*e){}return nil; }
UIImage *ABMCIconImageForBundleID(NSString *bundleID) { UIImage*i=ABMCAppListIcon(bundleID,59);return i?:ABMCIconImageForProxy(ABMCProxy(bundleID)); }
UIImage *ABMCIconImage(NSString *token) { UIImageSymbolConfiguration*c=[UIImageSymbolConfiguration configurationWithPointSize:22 weight:UIImageSymbolWeightMedium];UIImage*s=token.length?[UIImage systemImageNamed:token withConfiguration:c]:nil;return s?:ABMCIconImageForBundleID(token)?:[UIImage systemImageNamed:@"app.fill" withConfiguration:c]; }
UIImage *ABMCTintedIcon(NSString *token,UIColor *color) { UIImage*i=ABMCIconImage(token);return[UIImage systemImageNamed:token]?[i imageWithTintColor:color renderingMode:UIImageRenderingModeAlwaysOriginal]:i; }
NSString *ABMCInferLinkIcon(NSString *url) {NSString*s=[NSURL URLWithString:url].scheme.lowercaseString;if([s isEqualToString:@"http"]||[s isEqualToString:@"https"])return @"safari.fill";if([s isEqualToString:@"weixin"])return @"com.tencent.xin";if([s isEqualToString:@"alipay"])return @"com.alipay.iphoneclient";if([s isEqualToString:@"mailto"])return @"envelope.fill";if([s isEqualToString:@"tel"]||[s isEqualToString:@"sms"])return @"phone.fill";return @"link"; }
NSString *ABMCApplicationName(NSString *bundleID) {NSString*n=ABMCAppListDisplayName(bundleID);if(n.length)return n;n=ABMCValue(ABMCProxy(bundleID),@"localizedName");return n.length?n:(bundleID?:@"未知应用");}
BOOL ABMCIsAllowedStoreApplicationProxy(id proxy) {if(!proxy)return NO;@try{NSString*bid=ABMCValue(proxy,@"bundleIdentifier");NSURL*u=ABMCValue(proxy,@"bundleURL");NSString*p=u.path;NSString*t=ABMCValue(proxy,@"applicationType");BOOL user=[p hasPrefix:@"/var/containers/Bundle/Application/"]||[p hasPrefix:@"/private/var/containers/Bundle/Application/"]||[p containsString:@"/TrollStore/"];if(!bid.length||![t isEqualToString:@"User"]||![p.pathExtension.lowercaseString isEqualToString:@"app"]||!user)return NO;for(NSString*x in @[@"Service",@"service",@"UIService",@"Helper",@"Widget",@"appex",@"/PlugIns/",@"/Extensions/"])if([p containsString:x])return NO;return YES;}@catch(NSException*e){return NO;} }
NSDictionary *ABMCAppListApplications(NSArray **sortedIdentifiers) {id list=ABMCAppList();if(!list)return nil;SEL s=NSSelectorFromString(@"applicationsFilteredUsingPredicate:onlyVisible:titleSortedIdentifiers:");NSArray*ids=nil;NSDictionary*apps=list&&[list respondsToSelector:s]?((id(*)(id,SEL,id,BOOL,NSArray**))objc_msgSend)(list,s,[NSPredicate predicateWithValue:YES],YES,&ids):nil;if(sortedIdentifiers)*sortedIdentifiers=ids;return apps;}
