#import "ABMCUIHelpers.h"
#import <objc/message.h>

@interface UIImage (ABMCIconPrivate)
+ (instancetype)_applicationIconImageForBundleIdentifier:(NSString *)identifier format:(int)format scale:(CGFloat)scale;
@end

static id ABMCObject(id object, NSString *name) { SEL selector=NSSelectorFromString(name);return object&&[object respondsToSelector:selector]?((id(*)(id,SEL))objc_msgSend)(object,selector):nil; }
static BOOL ABMCBool(id object, NSString *name) { SEL selector=NSSelectorFromString(name);return object&&[object respondsToSelector:selector]?((BOOL(*)(id,SEL))objc_msgSend)(object,selector):NO; }
NSString *ABMCBundleIdentifierForApplication(id app) { id value=ABMCObject(app,@"bundleIdentifier");return[value isKindOfClass:NSString.class]?value:nil; }
NSString *ABMCDisplayNameForApplication(id app) { NSString *name=ABMCObject(app,@"localizedName");if(name.length)return name;NSURL *url=ABMCObject(app,@"bundleURL");NSDictionary *info=[NSBundle bundleWithURL:url].infoDictionary;return info[@"CFBundleDisplayName"]?:info[@"CFBundleName"]?:info[@"CFBundleExecutable"]; }

static BOOL IsUsable(id app) { NSString*bid=ABMCBundleIdentifierForApplication(app);NSURL*url=ABMCObject(app,@"bundleURL");NSString*path=url.path;NSString*type=ABMCObject(app,@"applicationType");if(!bid.length||!path.length||![path.pathExtension.lowercaseString isEqualToString:@"app"])return NO;if(![type isEqualToString:@"User"]&&![type isEqualToString:@"System"])return NO;if(ABMCBool(app,@"launchProhibited")||ABMCBool(app,@"isLaunchProhibited"))return NO;for(NSString*part in @[@"/PlugIns/",@"/Extensions/",@".appex",@"UIService",@"Service",@"Helper",@"Widget"])if([path containsString:part])return NO;return YES; }
ABMCApplicationKind ABMCApplicationKindForProxy(id app) { NSURL*url=ABMCObject(app,@"bundleURL");NSString*path=url.path;NSString*type=ABMCObject(app,@"applicationType");NSString*container=[path stringByDeletingLastPathComponent];if([[NSFileManager defaultManager]fileExistsAtPath:[container stringByAppendingPathComponent:@"_TrollStore"]]||[[NSFileManager defaultManager]fileExistsAtPath:[container stringByAppendingPathComponent:@"_TrollStoreLite"]]||[path rangeOfString:@"TrollStore" options:NSCaseInsensitiveSearch].location!=NSNotFound)return ABMCApplicationKindTrollStore;return[type isEqualToString:@"System"]?ABMCApplicationKindSystem:ABMCApplicationKindUser; }
NSArray *ABMCInstalledApplications(void) { Class c=NSClassFromString(@"LSApplicationWorkspace");SEL d=NSSelectorFromString(@"defaultWorkspace"),e=NSSelectorFromString(@"enumerateApplicationsOfType:block:");id w=c&&[c respondsToSelector:d]?((id(*)(id,SEL))objc_msgSend)(c,d):nil;if(!w)return @[];NSMutableArray*raw=[NSMutableArray array];if([w respondsToSelector:e]){void(^block)(id)=^(id app){if(app)[raw addObject:app];};((void(*)(id,SEL,NSInteger,id))objc_msgSend)(w,e,0,block);((void(*)(id,SEL,NSInteger,id))objc_msgSend)(w,e,1,block);}else{NSArray*a=ABMCObject(w,@"allInstalledApplications");if([a isKindOfClass:NSArray.class])[raw addObjectsFromArray:a];}NSMutableArray*out=[NSMutableArray array];NSMutableSet*seen=[NSMutableSet set];for(id app in raw){NSString*bid=ABMCBundleIdentifierForApplication(app);if(IsUsable(app)&&bid.length&&![seen containsObject:bid]){[seen addObject:bid];[out addObject:app];}}return out; }
static UIImage *Scale(UIImage *image) {if(!image)return nil;CGFloat d=29;UIGraphicsBeginImageContextWithOptions(CGSizeMake(d,d),NO,UIScreen.mainScreen.scale);[image drawInRect:CGRectMake(0,0,d,d)];UIImage*r=UIGraphicsGetImageFromCurrentImageContext();UIGraphicsEndImageContext();return r;}
UIImage *ABMCIconImageForBundleID(NSString *bid) {if(!bid.length)return nil;@try{return Scale([UIImage _applicationIconImageForBundleIdentifier:bid format:0 scale:UIScreen.mainScreen.scale]);}@catch(NSException*e){return nil;}}
UIImage *ABMCIconImageForProxy(id app){return ABMCIconImageForBundleID(ABMCBundleIdentifierForApplication(app));}
UIImage *ABMCIconImage(NSString *token){UIImageSymbolConfiguration*c=[UIImageSymbolConfiguration configurationWithPointSize:20 weight:UIImageSymbolWeightMedium];UIImage*s=[UIImage systemImageNamed:token withConfiguration:c];return s?:ABMCIconImageForBundleID(token)?:[UIImage systemImageNamed:@"app.fill" withConfiguration:c];}
UIImage *ABMCTintedIcon(NSString *token,UIColor *color){UIImage*i=ABMCIconImage(token);return[UIImage systemImageNamed:token]?[i imageWithTintColor:color renderingMode:UIImageRenderingModeAlwaysOriginal]:i;}
NSString *ABMCInferLinkIcon(NSString *url){NSString*s=[NSURL URLWithString:url].scheme.lowercaseString;if([s isEqualToString:@"weixin"])return @"com.tencent.xin";if([s isEqualToString:@"alipay"])return @"com.alipay.iphoneclient";if([s isEqualToString:@"http"]||[s isEqualToString:@"https"])return @"safari.fill";if([s isEqualToString:@"mailto"])return @"envelope.fill";if([s isEqualToString:@"tel"]||[s isEqualToString:@"sms"])return @"phone.fill";return @"link";}
NSString *ABMCApplicationName(NSString *bid){for(id app in ABMCInstalledApplications())if([ABMCBundleIdentifierForApplication(app)isEqualToString:bid])return ABMCDisplayNameForApplication(app)?:bid;return bid?:@"未知应用";}
