#import "ABMCLinkListController.h"
#import "ABMCUIHelpers.h"
#define D CFSTR("com.huynguyen.actionbuttonmulticlick")
static NSString *ValidURL(NSString*v){v=[v stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if(!v.length||v.length>4096)return nil;if(![NSURL URLWithString:v].scheme.length&&[v containsString:@"."])v=[@"https://" stringByAppendingString:v];return [NSURL URLWithString:v].scheme.length?v:nil;}
@interface ABMCLinkListController ()<UISearchBarDelegate>@end
@implementation ABMCLinkListController{NSString*_key,*_query;NSMutableArray*_links;}
- (instancetype)initWithPreferenceKey:(NSString*)key{if((self=[super initWithStyle:UITableViewStyleInsetGrouped])){_key=[key copy];self.title=@"URL";}return self;}
- (void)viewDidLoad{[super viewDidLoad];_query=@"";self.tableView.rowHeight=44.0;self.tableView.estimatedRowHeight=44.0;[self installSearchHeader];UIButton *addButton=[UIButton buttonWithType:UIButtonTypeSystem];addButton.frame=CGRectMake(0,0,52,32);[addButton setTitle:@"添加" forState:UIControlStateNormal];addButton.titleLabel.font=[UIFont systemFontOfSize:17.0];[addButton addTarget:self action:@selector(add) forControlEvents:UIControlEventTouchUpInside];UILongPressGestureRecognizer *importPress=[[UILongPressGestureRecognizer alloc]initWithTarget:self action:@selector(importPress:)];importPress.minimumPressDuration=.45;importPress.cancelsTouchesInView=YES;[addButton addGestureRecognizer:importPress];UIBarButtonItem*add=[[UIBarButtonItem alloc]initWithCustomView:addButton];self.navigationItem.rightBarButtonItems=@[add];[self load];}
- (void)installSearchHeader {
    CGFloat width=self.tableView.bounds.size.width;if(width<100)width=UIScreen.mainScreen.bounds.size.width;
    UIView *header=[[UIView alloc]initWithFrame:CGRectMake(0,0,width,60)];header.autoresizingMask=UIViewAutoresizingFlexibleWidth;header.backgroundColor=UIColor.systemGroupedBackgroundColor;
    UISearchBar *search=[[UISearchBar alloc]initWithFrame:CGRectMake(20,0,width-40,56)];search.autoresizingMask=UIViewAutoresizingFlexibleWidth;search.placeholder=@"搜索 URL";search.delegate=self;[header addSubview:search];self.tableView.tableHeaderView=header;
}

- (void)load{_links=[NSMutableArray array];CFPropertyListRef v=CFPreferencesCopyAppValue(CFSTR("savedLinks"),D);if(v&&CFGetTypeID(v)==CFArrayGetTypeID())for(NSDictionary*x in (__bridge NSArray*)v)if([x[@"id"] length]&&[x[@"title"] length]&&[x[@"url"] length])[_links addObject:[x mutableCopy]];if(v)CFRelease(v);}
- (void)save{CFPreferencesSetAppValue(CFSTR("savedLinks"),(__bridge CFPropertyListRef)_links,D);CFPreferencesAppSynchronize(D);}

- (NSArray*)visible{return!_query.length?_links:[_links filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSDictionary*x,NSDictionary*b){return[x[@"title"] localizedCaseInsensitiveContainsString:_query]||[x[@"url"] localizedCaseInsensitiveContainsString:_query];}]];}
- (NSInteger)tableView:(UITableView*)t numberOfRowsInSection:(NSInteger)s{return self.visible.count;}
- (UITableViewCell*)tableView:(UITableView*)t cellForRowAtIndexPath:(NSIndexPath*)p{NSDictionary*x=self.visible[p.row];UITableViewCell*c=[t dequeueReusableCellWithIdentifier:@"url"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"url"];NSString*k=[@"link." stringByAppendingString:x[@"id"]],*token=ABMCDisplayIconToken(k,x[@"icon"]?:ABMCInferLinkIcon(x[@"url"]));ABMCApplyLargeIcon(c,ABMCTintedIcon(token,UIColor.systemBlueColor));c.textLabel.font=[UIFont systemFontOfSize:18];c.textLabel.text=ABMCDisplayTitle(k,x[@"title"]);NSString*a=[@"link:" stringByAppendingString:x[@"id"]];c.accessoryType=[ABMCSelectedActions(_key)containsObject:a]?UITableViewCellAccessoryCheckmark:0;ABMCInstallPresentationLongPress(c,self,k,c.textLabel.text,token,^{[self.tableView reloadData];});return c;}
- (void)tableView:(UITableView*)t didSelectRowAtIndexPath:(NSIndexPath*)p{NSString*a=[@"link:" stringByAppendingString:self.visible[p.row][@"id"]];NSMutableArray*x=[ABMCSelectedActions(_key)mutableCopy];if([x containsObject:a])[x removeObject:a];else if(x.count<8)[x addObject:a];else return;ABMCStoreSelectedActions(_key,x);[t reloadData];}
- (void)importPress:(UILongPressGestureRecognizer *)gesture { if(gesture.state==UIGestureRecognizerStateBegan)[self importClipboard]; }
- (UISwipeActionsConfiguration *)tableView:(UITableView *)tableView trailingSwipeActionsConfigurationForRowAtIndexPath:(NSIndexPath *)path { NSDictionary *item=self.visible[path.row]; UIContextualAction *remove=[UIContextualAction contextualActionWithStyle:UIContextualActionStyleDestructive title:@"删除" handler:^(__unused UIContextualAction *a,__unused UIView *v,void(^done)(BOOL)){[_links removeObject:item];[self save];[self.tableView reloadData];done(YES);}];return [UISwipeActionsConfiguration configurationWithActions:@[remove]]; }
- (void)importClipboard {
    NSString *text=UIPasteboard.generalPasteboard.string;
    NSArray<NSString *> *raw=[text componentsSeparatedByCharactersInSet:NSCharacterSet.newlineCharacterSet];
    NSMutableArray *lines=[NSMutableArray array];for(NSString *line in raw){NSString *v=[line stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if(v.length)[lines addObject:v];}
    NSUInteger imported=0;
    for(NSUInteger i=0;i+2<lines.count;i+=3){NSString *title=lines[i],*url=ValidURL(lines[i+1]),*icon=lines[i+2];if(!title.length||!url.length)continue;BOOL duplicate=NO;for(NSDictionary *old in _links)if([old[@"url"] isEqualToString:url]||[old[@"title"] isEqualToString:title]){duplicate=YES;break;}if(duplicate)continue;[_links addObject:[@{@"id":NSUUID.UUID.UUIDString,@"title":title,@"url":url,@"icon":icon.length?icon:ABMCInferLinkIcon(url)}mutableCopy]];imported++;}
    if(imported){[self save];[self.tableView reloadData];}
    NSString *message=imported?[NSString stringWithFormat:@"已导入 %lu 个链接。",(unsigned long)imported]:@"未找到有效的三行格式链接。\n格式：名称、URL、图标 Bundle ID 或 SF Symbol。";
    UIAlertController *alert=[UIAlertController alertControllerWithTitle:@"导入链接" message:message preferredStyle:UIAlertControllerStyleAlert];[alert addAction:[UIAlertAction actionWithTitle:@"好" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:alert animated:YES completion:nil];
}
- (void)add { UIAlertController *alert=[UIAlertController alertControllerWithTitle:@"新增 URL" message:@"第三项可填写 SF Symbol 名称，或应用 Bundle ID。留空会自动识别。" preferredStyle:UIAlertControllerStyleAlert];[alert addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"URL 名称";}];[alert addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"网页地址或 URL Scheme";f.autocapitalizationType=UITextAutocapitalizationTypeNone;}];[alert addTextFieldWithConfigurationHandler:^(UITextField *f){f.placeholder=@"SF 图标名或应用标识符（可选）";f.autocapitalizationType=UITextAutocapitalizationTypeNone;}];[alert addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[alert addAction:[UIAlertAction actionWithTitle:@"保存" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction *a){NSString *title=[alert.textFields[0].text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet],*url=ValidURL(alert.textFields[1].text),*icon=[alert.textFields[2].text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if(!title.length||!url.length)return;[_links addObject:[@{@"id":NSUUID.UUID.UUIDString,@"title":title,@"url":url,@"icon":icon.length?icon:ABMCInferLinkIcon(url)}mutableCopy]];[self save];[self.tableView reloadData];}]];[self presentViewController:alert animated:YES completion:nil];}

- (void)searchBar:(UISearchBar*)s textDidChange:(NSString*)text{_query=[text copy]?:@"";[self.tableView reloadData];}@end
