#import "ABMCIconStyleController.h"
#import "ABMCUIHelpers.h"
#import <math.h>
#define Domain CFSTR("com.huynguyen.actionbuttonmulticlick")
#define Changed CFSTR("com.huynguyen.actionbuttonmulticlick/prefsChanged")
#define SizeKey CFSTR("unifiedIconSize")
#define ColorKey CFSTR("unifiedIconColor")
#define TextSizeKey CFSTR("unifiedTextSize")
#define TextColorEnabledKey CFSTR("unifiedTextColorEnabled")
#define TextColorKey CFSTR("unifiedTextColor")

@implementation ABMCIconStyleController { ABMCIconStyleMode _mode; UITextField *_field; UIColorWell *_well; }
- (instancetype)initWithMode:(ABMCIconStyleMode)mode { if((self=[super initWithStyle:UITableViewStyleInsetGrouped])){_mode=mode;self.title=mode==ABMCIconStyleModeSize?@"图标尺寸":(mode==ABMCIconStyleModeColor?@"图标颜色":(mode==ABMCIconStyleModeTextSize?@"文字尺寸":@"文字颜色"));}return self; }
- (instancetype)init { return [self initWithMode:ABMCIconStyleModeSize]; }
- (void)viewDidLoad {[super viewDidLoad];self.navigationItem.rightBarButtonItem=nil;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return (_mode==ABMCIconStyleModeSize || _mode==ABMCIconStyleModeTextSize)?1:(_mode==ABMCIconStyleModeTextColor?3:2);}
- (NSString *)tableView:(UITableView *)t titleForFooterInSection:(NSInteger)s{return _mode==ABMCIconStyleModeSize?@"当前大小以 pt 显示。请输入 12–48，保存后全局图标立即使用此尺寸。":(_mode==ABMCIconStyleModeTextSize?@"当前大小以 pt 显示。请输入 14–28，主分页、四个分类页与已选动作横幅都会立即使用。":@"开启后以指定颜色显示所有动作名称；关闭时保留系统默认文字颜色。可输入 #RRGGBB 或点颜色块选择。 ");}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p { UITableViewCell*c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:nil]; BOOL textSize=_mode==ABMCIconStyleModeTextSize, size=_mode==ABMCIconStyleModeSize; if(size||textSize){c.textLabel.text=textSize?@"文字大小（pt）":@"图标大小（pt）";_field=[[UITextField alloc]initWithFrame:CGRectMake(0,0,118,38)];_field.textAlignment=NSTextAlignmentRight;_field.keyboardType=UIKeyboardTypeDecimalPad;_field.text=[NSString stringWithFormat:@"%.0f",textSize?ABMCUnifiedTextSize():ABMCUnifiedIconSize()];_field.placeholder=textSize?@"18":@"30";_field.clearButtonMode=UITextFieldViewModeWhileEditing;[_field addTarget:self action:@selector(fieldChanged:) forControlEvents:UIControlEventEditingChanged];c.accessoryView=_field;return c;} if(_mode==ABMCIconStyleModeTextColor&&p.row==0){c.textLabel.text=@"启用自定义文字颜色";UISwitch*sw=[UISwitch new];sw.on=ABMCUsesUnifiedTextColor();[sw addTarget:self action:@selector(enabledChanged:) forControlEvents:UIControlEventValueChanged];c.accessoryView=sw;return c;}NSInteger colorRow=_mode==ABMCIconStyleModeTextColor?1:0;if(p.row==colorRow){c.textLabel.text=@"十六进制";_field=[[UITextField alloc]initWithFrame:CGRectMake(0,0,118,38)];_field.textAlignment=NSTextAlignmentRight;_field.keyboardType=UIKeyboardTypeASCIICapable;_field.text=_mode==ABMCIconStyleModeTextColor?ABMCUnifiedTextColorHex():ABMCUnifiedIconColorHex();_field.placeholder=_mode==ABMCIconStyleModeTextColor?@"#000000":@"#007AFF";_field.autocapitalizationType=UITextAutocapitalizationTypeAllCharacters;[_field addTarget:self action:@selector(fieldChanged:) forControlEvents:UIControlEventEditingChanged];c.accessoryView=_field;return c;}c.textLabel.text=@"颜色盘";_well=[[UIColorWell alloc]initWithFrame:CGRectMake(0,0,44,32)];_well.selectedColor=_mode==ABMCIconStyleModeTextColor?ABMCUnifiedTextColor():ABMCUnifiedIconColor();[_well addTarget:self action:@selector(colorChanged:) forControlEvents:UIControlEventValueChanged];c.accessoryView=_well;return c;}
- (NSString *)hex:(UIColor *)c {CGFloat r=0,g=0,b=0,a=0;if(![c getRed:&r green:&g blue:&b alpha:&a])return @"#007AFF";return[NSString stringWithFormat:@"#%02lX%02lX%02lX",lround(r*255),lround(g*255),lround(b*255)];}
- (void)enabledChanged:(UISwitch *)sw { CFPreferencesSetAppValue(TextColorEnabledKey,sw.on?kCFBooleanTrue:kCFBooleanFalse,Domain);CFPreferencesAppSynchronize(Domain);CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(),Changed,NULL,NULL,YES);}
- (void)colorChanged:(UIColorWell *)well {_field.text=[self hex:well.selectedColor];[self save];}
- (UIColor *)color:(NSString *)s {s=[[[s?:@"" stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]uppercaseString]stringByReplacingOccurrencesOfString:@"#" withString:@""];unsigned v=0;NSScanner*scan=[NSScanner scannerWithString:s];if(s.length!=6||![scan scanHexInt:&v]||!scan.isAtEnd)return nil;return[UIColor colorWithRed:((v>>16)&255)/255.0 green:((v>>8)&255)/255.0 blue:(v&255)/255.0 alpha:1];}
- (void)fieldChanged:(UITextField *)field { [self save]; }
- (void)viewWillDisappear:(BOOL)animated {[super viewWillDisappear:animated];[self save];}
- (void)save {if(_mode==ABMCIconStyleModeSize || _mode==ABMCIconStyleModeTextSize){CGFloat size=[_field.text doubleValue];CGFloat low=_mode==ABMCIconStyleModeTextSize?14:12,high=_mode==ABMCIconStyleModeTextSize?28:48;if(size<low||size>high)return;CFPreferencesSetAppValue(_mode==ABMCIconStyleModeTextSize?TextSizeKey:SizeKey,(__bridge CFPropertyListRef)@(size),Domain);}else{UIColor*c=[self color:_field.text]?:_well.selectedColor;if(!c)return;CFPreferencesSetAppValue(_mode==ABMCIconStyleModeTextColor?TextColorKey:ColorKey,(__bridge CFPropertyListRef)[self hex:c],Domain);}CFPreferencesAppSynchronize(Domain);CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(),Changed,NULL,NULL,YES);}
@end
