#import "ABMCActionListController.h"
#import "ABMCApplicationListController.h"
#import "ABMCAppShortcutListController.h"
#import "ABMCShortcutListController.h"
#import "ABMCLinkListController.h"
#import "ABMCPresetLinkController.h"
#import "ABMCBuiltinListController.h"
#import "ABMCUIHelpers.h"
#import <Preferences/PSSpecifier.h>

#define Domain CFSTR("com.huynguyen.actionbuttonmulticlick")
#define TestNotice CFSTR("com.huynguyen.actionbuttonmulticlick/testCurrentAction")
#define LinksKey CFSTR("savedLinks")
typedef struct { NSString *identifier; NSString *title; NSString *icon; } Action;
static const Action kActions[] = {
    {@"default",@"系统默认",@"gearshape.fill"},{@"flashlight",@"手电筒",@"flashlight.on.fill"},{@"camera",@"相机",@"camera.fill"},{@"silent",@"静音切换",@"bell.slash.fill"},{@"screenshot",@"截屏",@"viewfinder"},{@"lock",@"锁屏",@"lock.fill"},{@"controlCenter",@"控制中心",@"switch.2"},{@"notificationCenter",@"通知中心",@"bell.fill"},{@"settings",@"打开设置",@"gearshape.fill"},{@"respring",@"重启界面",@"arrow.clockwise"},{@"none",@"无操作",@"nosign"}
};
static NSString *LinkTitle(NSString *identifier) {CFPropertyListRef value=CFPreferencesCopyAppValue(LinksKey,Domain);NSString*title=nil;if(value&&CFGetTypeID(value)==CFArrayGetTypeID())for(NSDictionary*x in (__bridge NSArray*)value)if([x isKindOfClass:NSDictionary.class]&&[x[@"id"]isEqualToString:identifier]){title=[x[@"title"]copy];break;}if(value)CFRelease(value);return title;}
static NSString *ActionTitle(NSString *action){if(!action.length||[action isEqualToString:@"none"])return @"无操作";for(NSUInteger i=0;i<sizeof(kActions)/sizeof(kActions[0]);i++)if([action isEqualToString:kActions[i].identifier])return kActions[i].title;if([action hasPrefix:@"app:"])return ABMCApplicationName([action substringFromIndex:4]);if([action hasPrefix:@"appshortcut:"]){NSArray*p=[[action substringFromIndex:12]componentsSeparatedByString:@"|"];return p.count>2&&[p[2] length]?p[2]:(p.count?ABMCApplicationName(p[0]):@"快捷方式");}if([action hasPrefix:@"shortcutid:"]){NSArray*p=[[action substringFromIndex:11]componentsSeparatedByString:@"|"];return p.count>1?p[1]:@"快捷指令";}if([action hasPrefix:@"shortcut:"])return[action substringFromIndex:9];if([action hasPrefix:@"link:"])return LinkTitle([action substringFromIndex:5])?:@"链接（未找到）";if([action hasPrefix:@"url:"])return[action substringFromIndex:4];return action;}
static UIImage *ActionIcon(NSString *action){for(NSUInteger i=0;i<sizeof(kActions)/sizeof(kActions[0]);i++)if([action isEqualToString:kActions[i].identifier])return ABMCTintedIcon(kActions[i].icon,UIColor.systemBlueColor);if([action hasPrefix:@"app:"])return ABMCIconImageForBundleID([action substringFromIndex:4]);if([action hasPrefix:@"appshortcut:"]){NSArray*p=[[action substringFromIndex:12]componentsSeparatedByString:@"|"];return p.count?ABMCIconImageForBundleID(p[0]):nil;}if([action hasPrefix:@"shortcutid:"])return ABMCShortcutIconForIdentifier([[[action substringFromIndex:11]componentsSeparatedByString:@"|"]firstObject]);if([action hasPrefix:@"link:"]||[action hasPrefix:@"url:"])return ABMCTintedIcon(@"link",UIColor.systemBlueColor);return ABMCTintedIcon(@"questionmark.circle",UIColor.systemBlueColor);}

@interface ABMCActionListController ()
@end
@implementation ABMCActionListController { NSString *_key,*_fallback,*_current; }
- (void)viewDidLoad {[super viewDidLoad];PSSpecifier*p=self.specifier;_key=[[p propertyForKey:@"key"]copy];_fallback=[[p propertyForKey:@"default"]copy];self.title=[p name].length?[p name]:@"选择动作";}
- (void)viewWillAppear:(BOOL)animated {[super viewWillAppear:animated];CFStringRef v=(CFStringRef)CFPreferencesCopyAppValue((__bridge CFStringRef)_key,Domain);_current=v?(__bridge_transfer NSString*)v:(_fallback?:@"none");_specifiers=nil;[self reloadSpecifiers];}
- (NSArray*)specifiers {if(!_specifiers){NSMutableArray*a=[NSMutableArray array];[a addObject:[PSSpecifier groupSpecifierWithName:@"已选动作"]];PSSpecifier*chosen=[PSSpecifier preferenceSpecifierNamed:ActionTitle(_current) target:self set:NULL get:NULL detail:Nil cell:PSStaticTextCell edit:Nil];[chosen setProperty:@YES forKey:@"selectedAction"];[a addObject:chosen];[a addObject:[PSSpecifier groupSpecifierWithName:@"动作测试"]];PSSpecifier*test=[PSSpecifier preferenceSpecifierNamed:@"开始测试" target:self set:NULL get:NULL detail:Nil cell:PSButtonCell edit:Nil];test->action=@selector(test:);[a addObject:test];NSArray*categories=@[@[@"基础动作",@"基础动作",@"builtin",@"hand.tap.fill"],@[@"打开应用",@"打开应用",@"app",@"app.badge.checkmark"],@[@"快捷方式",@"快捷方式",@"appshortcut",@"square.grid.2x2.fill"],@[@"快捷指令",@"快捷指令",@"shortcut",@"square.stack.3d.up.fill"],@[@"打开链接",@"打开链接",@"link",@"link"],@[@"预设链接",@"预设链接",@"preset",@"safari.fill"]];for(NSArray*x in categories){[a addObject:[PSSpecifier groupSpecifierWithName:x[0]]];PSSpecifier*s=[PSSpecifier preferenceSpecifierNamed:x[1] target:self set:NULL get:NULL detail:Nil cell:PSLinkCell edit:Nil];[s setProperty:x[2]forKey:@"category"];[s setProperty:x[3]forKey:@"iconToken"];s->action=@selector(open:);[a addObject:s];}_specifiers=a;}return _specifiers;}
- (UITableViewCell*)tableView:(UITableView*)tableView cellForRowAtIndexPath:(NSIndexPath*)path {UITableViewCell*c=[super tableView:tableView cellForRowAtIndexPath:path];PSSpecifier*s=[self specifierAtIndexPath:path];c.accessoryView=nil;c.imageView.hidden=NO;c.imageView.image=nil;c.textLabel.textColor=UIColor.labelColor;c.textLabel.font=[UIFont systemFontOfSize:18 weight:UIFontWeightRegular];if([s propertyForKey:@"selectedAction"]){ABMCApplyLargeIcon(c,ActionIcon(_current));}else{NSString*token=[s propertyForKey:@"iconToken"];if(token.length)ABMCApplyLargeIcon(c,ABMCTintedIcon(token,UIColor.systemBlueColor));}return c;}
- (void)open:(PSSpecifier*)s {NSString*c=[s propertyForKey:@"category"];UIViewController*v=nil;if([c isEqualToString:@"builtin"])v=[[ABMCBuiltinListController alloc]initWithPreferenceKey:_key];else if([c isEqualToString:@"app"])v=[[ABMCApplicationListController alloc]initWithPreferenceKey:_key];else if([c isEqualToString:@"appshortcut"])v=[[ABMCAppShortcutListController alloc]initWithPreferenceKey:_key];else if([c isEqualToString:@"shortcut"])v=[[ABMCShortcutListController alloc]initWithPreferenceKey:_key];else if([c isEqualToString:@"link"])v=[[ABMCLinkListController alloc]initWithPreferenceKey:_key];else if([c isEqualToString:@"preset"])v=[[ABMCPresetLinkController alloc]initWithPreferenceKey:_key];if(v)[self.navigationController pushViewController:v animated:YES];}
- (void)test:(PSSpecifier*)s {if(!_current.length||[_current isEqualToString:@"none"])return;CFPreferencesSetAppValue(CFSTR("testAction"),(__bridge CFPropertyListRef)_current,Domain);CFPreferencesAppSynchronize(Domain);CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(),TestNotice,NULL,NULL,YES);}
@end
