#import "ABMCShortcutListController.h"
#import "ABMCUIHelpers.h"
#import <objc/message.h>
#import <sqlite3.h>
#define Domain CFSTR("com.huynguyen.actionbuttonmulticlick")

static BOOL ValidID(NSString *v) { return [v isKindOfClass:NSString.class] && [[NSUUID alloc] initWithUUIDString:v] != nil; }

@interface ABMCShortcutListController () <UISearchBarDelegate>
@end
@implementation ABMCShortcutListController { NSString *_key,*_query; NSArray *_shortcuts,*_folders; }
- (instancetype)initWithPreferenceKey:(NSString *)key { if((self=[super initWithStyle:UITableViewStyleInsetGrouped])) { _key=[key copy]; self.title=@"指令列表"; } return self; }
- (void)viewDidLoad {
    [super viewDidLoad]; _query=@""; self.tableView.rowHeight=58;
    UIView *h=[[UIView alloc]initWithFrame:CGRectMake(0,0,UIScreen.mainScreen.bounds.size.width,72)]; UISearchBar *s=[[UISearchBar alloc]initWithFrame:CGRectInset(h.bounds,10,8)]; s.placeholder=@"搜索全部快捷指令";s.delegate=self;[h addSubview:s];self.tableView.tableHeaderView=h;
    UIBarButtonItem *native=[[UIBarButtonItem alloc]initWithTitle:@"原生面板" style:UIBarButtonItemStylePlain target:self action:@selector(openNativeShortcuts)];
    UIButton *clearButton=[UIButton buttonWithType:UIButtonTypeSystem];clearButton.frame=CGRectMake(0,0,48,32);[clearButton setTitle:@"清空" forState:UIControlStateNormal];UITapGestureRecognizer *single=[[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(clearCurrentTap:)];UITapGestureRecognizer *doubleTap=[[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(clearCategoryEverywhereTap:)];doubleTap.numberOfTapsRequired=2;[single requireGestureRecognizerToFail:doubleTap];[clearButton addGestureRecognizer:single];[clearButton addGestureRecognizer:doubleTap];self.navigationItem.rightBarButtonItems=@[[[UIBarButtonItem alloc]initWithCustomView:clearButton],native]; [self reloadData];
}
- (NSArray *)paths { return @[@"/private/var/mobile/Library/Shortcuts/Shortcuts.sqlite",@"/var/mobile/Library/Shortcuts/Shortcuts.sqlite",@"/private/var/mobile/Library/Shortcuts/Shortcuts.db",@"/var/mobile/Library/Shortcuts/Shortcuts.db"]; }
- (void)readPath:(NSString *)path shortcuts:(NSMutableDictionary *)shortcuts folders:(NSMutableDictionary *)folders {
    sqlite3 *db=NULL;if(sqlite3_open_v2(path.fileSystemRepresentation,&db,SQLITE_OPEN_READONLY|SQLITE_OPEN_NOMUTEX,NULL)!=SQLITE_OK){if(db)sqlite3_close(db);return;}
    sqlite3_stmt *s=NULL;const char *q="SELECT x.ZNAME,x.ZWORKFLOWID,COALESCE(i.ZGLYPHNUMBER,0),COALESCE(i.ZBACKGROUNDCOLORVALUE,0) FROM ZSHORTCUT x LEFT JOIN ZSHORTCUTICON i ON i.Z_PK=x.ZICON WHERE x.ZNAME IS NOT NULL AND x.ZWORKFLOWID IS NOT NULL AND COALESCE(x.ZTOMBSTONED,0)=0";
    if(sqlite3_prepare_v2(db,q,-1,&s,NULL)==SQLITE_OK)while(sqlite3_step(s)==SQLITE_ROW){const char *n=(const char *)sqlite3_column_text(s,0),*i=(const char *)sqlite3_column_text(s,1);if(!n||!i)continue;NSString *name=[[NSString stringWithUTF8String:n]stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet],*identifier=[[NSString stringWithUTF8String:i]uppercaseString];if(name.length&&ValidID(identifier))shortcuts[identifier]=@{ @"name":name,@"identifier":identifier,@"glyph":@(sqlite3_column_int64(s,2)),@"color":@(sqlite3_column_int64(s,3))};}if(s)sqlite3_finalize(s);
    // Core Data schemas differ between iOS releases. Discover the existing folder table/columns read-only.
    s=NULL; if(sqlite3_prepare_v2(db,"SELECT name FROM sqlite_master WHERE type='table' AND upper(name) LIKE '%FOLDER%'",-1,&s,NULL)==SQLITE_OK) while(sqlite3_step(s)==SQLITE_ROW){const char *raw=(const char *)sqlite3_column_text(s,0);if(!raw)continue;NSString *table=[NSString stringWithUTF8String:raw];NSString *sql=[NSString stringWithFormat:@"SELECT * FROM %@ LIMIT 128",table];sqlite3_stmt *rows=NULL;if(sqlite3_prepare_v2(db,sql.UTF8String,-1,&rows,NULL)!=SQLITE_OK)continue;int cols=sqlite3_column_count(rows),nameCol=-1,idCol=-1;for(int c=0;c<cols;c++){NSString *column=[NSString stringWithUTF8String:sqlite3_column_name(rows,c)];if([column containsString:@"NAME"])nameCol=c;if([column containsString:@"IDENTIFIER"]||[column containsString:@"UUID"])idCol=c;}while(sqlite3_step(rows)==SQLITE_ROW){const char *n=nameCol>=0?(const char *)sqlite3_column_text(rows,nameCol):NULL,*i=idCol>=0?(const char *)sqlite3_column_text(rows,idCol):NULL;if(n){NSString *name=[NSString stringWithUTF8String:n];NSString *identifier=i?[NSString stringWithUTF8String:i]:name;if(name.length)folders[identifier]=@{ @"name":name,@"identifier":identifier};}}sqlite3_finalize(rows);}if(s)sqlite3_finalize(s);sqlite3_close(db);
}
- (void)reloadData { NSMutableDictionary *shortcuts=[NSMutableDictionary dictionary],*folders=[NSMutableDictionary dictionary];for(NSString *path in self.paths)[self readPath:path shortcuts:shortcuts folders:folders];_shortcuts=[shortcuts.allValues sortedArrayUsingComparator:^NSComparisonResult(NSDictionary*a,NSDictionary*b){return[a[@"name"] localizedCaseInsensitiveCompare:b[@"name"]];}];_folders=[folders.allValues sortedArrayUsingComparator:^NSComparisonResult(NSDictionary*a,NSDictionary*b){return[a[@"name"] localizedCaseInsensitiveCompare:b[@"name"]];}];[self.tableView reloadData]; }
- (NSArray *)visible { if(!_query.length)return _shortcuts ?: @[];return[_shortcuts filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSDictionary *x,NSDictionary *b){return[x[@"name"] localizedCaseInsensitiveContainsString:self->_query];}]]; }
- (void)openNativeShortcuts { NSURL *url=[NSURL URLWithString:@"shortcuts://"];SEL open=NSSelectorFromString(@"openURL:options:completionHandler:");if([UIApplication.sharedApplication respondsToSelector:open])((void(*)(id,SEL,id,id,id))objc_msgSend)(UIApplication.sharedApplication,open,url,@{},nil); }
- (void)clearCurrentTap:(UITapGestureRecognizer *)gesture { ABMCStoreSelectedActions(_key,@[]);[self.tableView reloadData]; }
- (void)clearCategoryEverywhereTap:(UITapGestureRecognizer *)gesture { for(NSString *key in @[@"singleClickAction",@"doubleClickAction",@"longPressAction"]){NSMutableArray *items=[ABMCSelectedActions(key) mutableCopy];[items filterUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSString *a,NSDictionary *b){return ![a hasPrefix:@"shortcutid:"];}]];ABMCStoreSelectedActions(key,items);}[self.tableView reloadData]; }
- (void)showLimit { UIAlertController *a=[UIAlertController alertControllerWithTitle:@"最多 8 项" message:@"每个按键动作最多可选择 8 项。" preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"好" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:a animated:YES completion:nil]; }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t { return _folders.count ? 2 : 1; }
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)section { return _folders.count&&section==0 ? @"快捷指令文件夹（点按使用原生面板）" : nil; }
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)section { return _folders.count&&section==0 ? _folders.count : self.visible.count ?: 1; }
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p {
    UITableViewCell *c=[t dequeueReusableCellWithIdentifier:@"ShortcutCell"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"ShortcutCell"];
    if(_folders.count&&p.section==0){NSDictionary *f=_folders[p.row];ABMCApplyLargeIcon(c,ABMCTintedIcon(@"folder.fill",nil));c.textLabel.font=[UIFont systemFontOfSize:18];c.textLabel.text=f[@"name"];c.detailTextLabel.text=@"使用系统快捷指令原生界面";c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;return c;}
    NSArray *items=self.visible;if(!items.count){ABMCApplyLargeIcon(c,ABMCTintedIcon(@"exclamationmark.circle",UIColor.secondaryLabelColor));c.textLabel.text=@"未读取到快捷指令";c.detailTextLabel.text=@"请打开一次快捷指令 App 后刷新";c.selectionStyle=UITableViewCellSelectionStyleNone;c.accessoryType=UITableViewCellAccessoryNone;return c;}
    NSDictionary *i=items[p.row];NSString *showKey=[@"shortcut." stringByAppendingString:i[@"identifier"]],*token=ABMCDisplayIconToken(showKey,@"");ABMCApplyLargeIcon(c,ABMCTintedIcon(token,nil)?:ABMCIconImageForBundleID(token)?:ABMCWorkflowIconImage([i[@"glyph"]integerValue],[i[@"color"]longLongValue])?:ABMCTintedIcon(@"square.stack.3d.up.fill",nil));c.textLabel.font=[UIFont systemFontOfSize:18];c.textLabel.text=ABMCDisplayTitle(showKey,i[@"name"]);c.detailTextLabel.text=nil;c.selectionStyle=UITableViewCellSelectionStyleDefault;NSString *action=[NSString stringWithFormat:@"shortcutid:%@|%@|%@|%@",i[@"identifier"],i[@"name"],i[@"glyph"],i[@"color"]];c.accessoryType=[ABMCSelectedActions(_key) containsObject:action]?UITableViewCellAccessoryCheckmark:UITableViewCellAccessoryNone;ABMCInstallPresentationLongPress(c,self,showKey,c.textLabel.text,token,^{[self.tableView reloadData];});return c;
}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)p { if(_folders.count&&p.section==0){[self openNativeShortcuts];return;}NSArray *items=self.visible;if(!items.count)return;NSDictionary *i=items[p.row];NSString *action=[NSString stringWithFormat:@"shortcutid:%@|%@|%@|%@",i[@"identifier"],i[@"name"],i[@"glyph"],i[@"color"]];NSMutableArray *chosen=[ABMCSelectedActions(_key)mutableCopy];if([chosen containsObject:action])[chosen removeObject:action];else if(chosen.count<8)[chosen addObject:action];else{[self showLimit];return;}ABMCStoreSelectedActions(_key,chosen);[t reloadData]; }
- (void)searchBar:(UISearchBar *)s textDidChange:(NSString *)text { _query=[text copy]?:@"";[self.tableView reloadData]; }
@end
