#import "ABMCShortcutListController.h"
#import "ABMCUIHelpers.h"
#import <sqlite3.h>
static BOOL UUIDOK(NSString *value){return[value isKindOfClass:NSString.class]&&[[NSUUID alloc]initWithUUIDString:value]!=nil;}
@interface ABMCShortcutListController ()<UISearchBarDelegate>@end
@implementation ABMCShortcutListController { NSString *_key,*_query; NSArray *_all; }
- (instancetype)initWithPreferenceKey:(NSString *)key { if((self=[super initWithStyle:UITableViewStyleInsetGrouped])){_key=[key copy];self.title=@"指令列表";}return self; }
- (void)viewDidLoad {[super viewDidLoad];_query=@"";self.tableView.rowHeight=44.0;self.tableView.estimatedRowHeight=44.0;[self reloadData];}
- (void)refreshHeader { ABMCInstallStickyCategoryActionHeader(self,_key,@"搜索快捷指令"); }
- (void)reloadData { NSMutableDictionary *unique=[NSMutableDictionary dictionary];NSArray *paths=@[@"/private/var/mobile/Library/Shortcuts/Shortcuts.sqlite",@"/var/mobile/Library/Shortcuts/Shortcuts.sqlite",@"/private/var/mobile/Library/Shortcuts/Shortcuts.db",@"/var/mobile/Library/Shortcuts/Shortcuts.db"];for(NSString *path in paths){sqlite3 *db=NULL;if(sqlite3_open_v2(path.UTF8String,&db,SQLITE_OPEN_READONLY|SQLITE_OPEN_NOMUTEX,NULL)!=SQLITE_OK){if(db)sqlite3_close(db);continue;}const char *sql="SELECT x.ZNAME,x.ZWORKFLOWID,COALESCE(i.ZGLYPHNUMBER,0),COALESCE(i.ZBACKGROUNDCOLORVALUE,0) FROM ZSHORTCUT x LEFT JOIN ZSHORTCUTICON i ON i.Z_PK=x.ZICON WHERE x.ZNAME IS NOT NULL AND x.ZWORKFLOWID IS NOT NULL AND COALESCE(x.ZTOMBSTONED,0)=0";sqlite3_stmt *rows=NULL;if(sqlite3_prepare_v2(db,sql,-1,&rows,NULL)==SQLITE_OK)while(sqlite3_step(rows)==SQLITE_ROW){const char *rawName=(const char *)sqlite3_column_text(rows,0),*rawID=(const char *)sqlite3_column_text(rows,1);if(!rawName||!rawID)continue;NSString *name=[NSString stringWithUTF8String:rawName],*identifier=[[NSString stringWithUTF8String:rawID]uppercaseString];if(name.length&&UUIDOK(identifier))unique[identifier]=@{@"name":name,@"id":identifier,@"glyph":@(sqlite3_column_int64(rows,2)),@"color":@(sqlite3_column_int64(rows,3))};}if(rows)sqlite3_finalize(rows);sqlite3_close(db);}_all=[unique.allValues sortedArrayUsingComparator:^NSComparisonResult(NSDictionary *a,NSDictionary *b){return[a[@"name"] localizedCaseInsensitiveCompare:b[@"name"]];}];[self.tableView reloadData]; }
- (NSArray *)visible { return !_query.length?_all:[_all filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSDictionary *item,NSDictionary *bindings){return[item[@"name"] localizedCaseInsensitiveContainsString:_query];}]]; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{return self.visible.count?:1;}
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)path { UITableViewCell *cell=[tableView dequeueReusableCellWithIdentifier:@"shortcut"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"shortcut"];NSArray *shown=self.visible;if(!shown.count){cell.imageView.image=nil;cell.textLabel.text=@"未读取到快捷指令";cell.accessoryType=UITableViewCellAccessoryNone;return cell;}NSDictionary *item=shown[path.row];NSString *key=[@"shortcut." stringByAppendingString:item[@"id"]],*token=ABMCDisplayIconToken(key,@"");ABMCApplyLargeIcon(cell,ABMCTintedIcon(token,nil)?:ABMCWorkflowIconImage([item[@"glyph"] integerValue],[item[@"color"] longLongValue]));cell.textLabel.font=[UIFont systemFontOfSize:18];cell.textLabel.text=ABMCDisplayTitle(key,item[@"name"]);NSString *action=[NSString stringWithFormat:@"shortcutid:%@|%@|%@|%@",item[@"id"],item[@"name"],item[@"glyph"],item[@"color"]];cell.accessoryType=[ABMCSelectedActions(_key) containsObject:action]?UITableViewCellAccessoryCheckmark:UITableViewCellAccessoryNone;ABMCInstallPresentationLongPress(cell,self,key,cell.textLabel.text,token,^{[self.tableView reloadData];});return cell; }
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)path { NSArray *shown=self.visible;if(!shown.count)return;NSDictionary *item=shown[path.row];NSString *action=[NSString stringWithFormat:@"shortcutid:%@|%@|%@|%@",item[@"id"],item[@"name"],item[@"glyph"],item[@"color"]];NSMutableArray *selected=[ABMCSelectedActions(_key) mutableCopy];if([selected containsObject:action])[selected removeObject:action];else if(selected.count<8)[selected addObject:action];else return;ABMCStoreSelectedActions(_key,selected);[self refreshHeader];[tableView reloadData]; }
- (void)viewDidAppear:(BOOL)animated { [super viewDidAppear:animated]; [self refreshHeader]; }
- (void)viewDidLayoutSubviews { [super viewDidLayoutSubviews]; ABMCUpdateStickyCategoryActionHeader(self); }
- (void)viewDidDisappear:(BOOL)animated { [super viewDidDisappear:animated]; if(self.isMovingFromParentViewController || self.navigationController==nil) ABMCRemoveStickyCategoryActionHeader(self); }
- (void)searchBar:(UISearchBar *)searchBar textDidChange:(NSString *)text {_query=[text copy]?:@"";[self.tableView reloadData];}
@end
