#import "ABMCLinkListController.h"
#import "ABMCUIHelpers.h"
#define D CFSTR("com.huynguyen.actionbuttonmulticlick")
static NSString *ValidURL(NSString*v){v=[v stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if(!v.length||v.length>4096)return nil;if(![NSURL URLWithString:v].scheme.length&&[v containsString:@"."])v=[@"https://" stringByAppendingString:v];return [NSURL URLWithString:v].scheme.length?v:nil;}
@interface ABMCLinkListController ()<UISearchBarDelegate>@end
@implementation ABMCLinkListController{NSString*_key,*_query;NSMutableArray*_links;}
- (instancetype)initWithPreferenceKey:(NSString*)key{if((self=[super initWithStyle:UITableViewStyleInsetGrouped])){_key=[key copy];self.title=@"URL";}return self;}
- (void)viewDidLoad{[super viewDidLoad];_query=@"";UIView*h=ABMCSelectedActionsBanner(_key);CGFloat bannerHeight=h.bounds.size.height;for(UIView *subview in h.subviews){CGRect frame=subview.frame;frame.origin.y+=60;subview.frame=frame;}UISearchBar*s=[[UISearchBar alloc]initWithFrame:CGRectMake(8,0,h.bounds.size.width-16,56)];s.placeholder=@"搜索 URL";s.delegate=self;CGRect f=h.frame;f.size.height=bannerHeight+60;h.frame=f;[h addSubview:s];self.tableView.tableHeaderView=h;UIBarButtonItem*add=[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemAdd target:self action:@selector(add)];UIBarButtonItem*import=[[UIBarButtonItem alloc]initWithTitle:@"导入" style:UIBarButtonItemStylePlain target:self action:@selector(importClipboard)];UIBarButtonItem*clear=[[UIBarButtonItem alloc]initWithTitle:@"清空" style:UIBarButtonItemStylePlain target:self action:@selector(clearAll)];self.navigationItem.rightBarButtonItems=@[clear,add,import];[self load];}
- (void)load{_links=[NSMutableArray array];CFPropertyListRef v=CFPreferencesCopyAppValue(CFSTR("savedLinks"),D);if(v&&CFGetTypeID(v)==CFArrayGetTypeID())for(NSDictionary*x in (__bridge NSArray*)v)if([x[@"id"] length]&&[x[@"title"] length]&&[x[@"url"] length])[_links addObject:[x mutableCopy]];if(v)CFRelease(v);}
- (void)save{CFPreferencesSetAppValue(CFSTR("savedLinks"),(__bridge CFPropertyListRef)_links,D);CFPreferencesAppSynchronize(D);}
- (void)clearAll{ABMCStoreSelectedActions(_key,@[]);self.tableView.tableHeaderView=ABMCSelectedActionsBanner(_key);[self.tableView reloadData];}
- (NSArray*)visible{return!_query.length?_links:[_links filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSDictionary*x,NSDictionary*b){return[x[@"title"] localizedCaseInsensitiveContainsString:_query]||[x[@"url"] localizedCaseInsensitiveContainsString:_query];}]];}
- (NSInteger)tableView:(UITableView*)t numberOfRowsInSection:(NSInteger)s{return self.visible.count;}
- (UITableViewCell*)tableView:(UITableView*)t cellForRowAtIndexPath:(NSIndexPath*)p{NSDictionary*x=self.visible[p.row];UITableViewCell*c=[t dequeueReusableCellWithIdentifier:@"url"]?:[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"url"];NSString*k=[@"link." stringByAppendingString:x[@"id"]],*token=ABMCDisplayIconToken(k,x[@"icon"]?:ABMCInferLinkIcon(x[@"url"]));ABMCApplyLargeIcon(c,ABMCTintedIcon(token,UIColor.systemBlueColor));c.textLabel.font=[UIFont systemFontOfSize:18];c.textLabel.text=ABMCDisplayTitle(k,x[@"title"]);c.detailTextLabel.text=x[@"url"];NSString*a=[@"link:" stringByAppendingString:x[@"id"]];c.accessoryType=[ABMCSelectedActions(_key)containsObject:a]?UITableViewCellAccessoryCheckmark:0;ABMCInstallPresentationLongPress(c,self,k,c.textLabel.text,token,^{[self.tableView reloadData];});return c;}
- (void)tableView:(UITableView*)t didSelectRowAtIndexPath:(NSIndexPath*)p{NSString*a=[@"link:" stringByAppendingString:self.visible[p.row][@"id"]];NSMutableArray*x=[ABMCSelectedActions(_key)mutableCopy];if([x containsObject:a])[x removeObject:a];else if(x.count<8)[x addObject:a];else return;ABMCStoreSelectedActions(_key,x);self.tableView.tableHeaderView=ABMCSelectedActionsBanner(_key);[t reloadData];}
- (void)importClipboard {
    NSString *text=UIPasteboard.generalPasteboard.string;
    NSArray<NSString *> *raw=[text componentsSeparatedByCharactersInSet:NSCharacterSet.newlineCharacterSet];
    NSMutableArray *lines=[NSMutableArray array];for(NSString *line in raw){NSString *v=[line stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];if(v.length)[lines addObject:v];}
    NSUInteger imported=0;
    for(NSUInteger i=0;i+2<lines.count;i+=3){NSString *title=lines[i],*url=ValidURL(lines[i+1]),*icon=lines[i+2];if(!title.length||!url.length)continue;BOOL duplicate=NO;for(NSDictionary *old in _links)if([old[@"url"] isEqualToString:url]||[old[@"title"] isEqualToString:title]){duplicate=YES;break;}if(duplicate)continue;[_links addObject:[@{@"id":NSUUID.UUID.UUIDString,@"title":title,@"url":url,@"icon":icon.length?icon:ABMCInferLinkIcon(url)}mutableCopy]];imported++;}
    if(imported){[self save];[self.tableView reloadData];}
    NSString *message=imported?[NSString stringWithFormat:@"已导入 %lu 个链接。",(unsigned long)imported]:@"未找到有效的三行格式链接。\n格式：名称、URL、图标 Bundle ID 或 SF Symbol。";
    UIAlertController *alert=[UIAlertController alertControllerWithTitle:@"导入链接" message:message preferredStyle:UIAlertControllerStyleAlert];[alert addAction:[UIAlertAction actionWithTitle:@"好" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:alert animated:YES completion:nil];
}
- (void)add{UIAlertController*a=[UIAlertController alertControllerWithTitle:@"新增 URL" message:nil preferredStyle:UIAlertControllerStyleAlert];[a addTextFieldWithConfigurationHandler:^(UITextField*f){f.placeholder=@"名称";}];[a addTextFieldWithConfigurationHandler:^(UITextField*f){f.placeholder=@"URL";}];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[a addAction:[UIAlertAction actionWithTitle:@"保存" style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction*z){NSString*u=ValidURL(a.textFields[1].text),*n=a.textFields[0].text;if(n.length&&u.length){[_links addObject:[@{@"id":NSUUID.UUID.UUIDString,@"title":n,@"url":u,@"icon":ABMCInferLinkIcon(u)}mutableCopy]];[self save];[self.tableView reloadData];}}]];[self presentViewController:a animated:YES completion:nil];}
- (void)searchBar:(UISearchBar*)s textDidChange:(NSString*)text{_query=[text copy]?:@"";[self.tableView reloadData];}@end
